### PR TITLE
Workaround for GAP 4.12 test failure due to new GAPDoc version

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Hmm, I think there are more places that need to be adjusted...

Perhaps a better approach is to modify `ci/run-gap-testinstall.g` to delete the offending .tst file

**Comment by fingolfin** [comment]
OK that should be better, I think.

**Comment by fingolfin** [comment]
@james-d-mitchell seems to work

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin sorry I didn't have time to do it myself. I'll merge and make a new release as soon as I can

**Pull request merged**
