### PR TITLE
Fix IsomorphismPermGroup related failures in translat.tst

### PR DESCRIPTION
**Pull request by flsmith**

### CODE REVIEW

**Comment by fingolfin** [comment]
I assume this addresses parts of issue #905, great

**Comment by fingolfin** [comment]
Someone needs to restart the tests against the latest version of the code in the repo, e.g. by closing and reopening this PR. Perhaps @james-d-mitchell can do it?

**Comment by fingolfin** [comment]
I applied the two of these changes in PR #909 which are needed to make the tests pass. But I think the other ones in here might still be worthwhile to future-proof the tests.

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin much appreciated

**Comment by james-d-mitchell** [comment]
This was superseded by #909, thanks @flsmith!

**Pull request closed without merging**
