### PR TITLE
Freeband

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
This PR supercedes PR #683 (it justs adds a reference to PR #683) and is rebased over the current master branch.

**Comment by wilfwilson** [comment]
@james-d-mitchell Is it alright if we do a squash-and-merge, and/or ask the PR author(s) to tidy up their commits, before merging big PRs like this? I don't mean to be precious/OCD about it, but in this case, for instance, there are 17 separate commits with not-always-descriptive names, and that means there's a bit more friction when going through the version control history (as I'm doing now).

**Comment by james-d-mitchell** [comment]
Yes, absolutely, this was my mistake, I meant to squash and merge but didn't, I completely agree with all your comments, this was my bad :(

**Comment by wilfwilson** [comment]
No worries James! Just wanted to make sure we are on the same page 🙂

**Pull request merged**
