### PR TITLE
Replace internal GAP names by official counterparts

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin I’m happy to merge this but will need to fix the CI first.

**Comment by fingolfin** [comment]
The CI fails due to some linter issue. As far as I understand, it finds a line too long. But I have no idea what the rules are, and how I should "correctly" wrap the line to make it happy -- can I just insert a newline at any point I like? How much do I have to indent it?

**Comment by fingolfin** [comment]
I've now tried to side step the problem by splitting the computation into two steps

**Comment by fingolfin** [comment]
The linter now dies with
```
gap/congruences/conglatt.gi:324: Pointless assignment immediately returned [0]
gap/congruences/congrms.gi:205: Pointless assignment immediately returned [0]
gap/greens/grac.gi:2072: Pointless assignment immediately returned [0]
gap/tools/iterators.gi:420: Pointless assignment immediately returned [0]
Analysed 325 files, found 4 errors!
```
But I did not even touch any of these files :-(

**Comment by james-d-mitchell** [comment]
@fingolfin Thanks! I recently updated gaplint, and it seems that the linting for the package is broken. I'll fix this asap.

**Comment by james-d-mitchell** [comment]
I've added these changes to PR #802, hoping to make a release later today!

**Comment by james-d-mitchell** [comment]
Resolved in v4.0.0

**Pull request closed without merging**
