### PR TITLE
build: detect C++ stdlib

### LINKED ISSUE #928: do not link libstdc++ unconditionally
https://github.com/semigroups/Semigroups/blob/4056547e7130abab1700e6056429600196a192bd/Makefile.in#L7

By right, with clang toolchain, the correct library is libc++
The present config causes breakage on arm64 (M1) macOS as reported on GAP Forum (and we tracked this down to this place)
```
Date: Fri, 23 Jun 2023 11:50:40 +0200
From: lfsequeira <forum@gap-system.org>
To: forum@gap-system.org
Subject: [GAP Forum] Loading packages on Apple Silicon Macs
X-Mailer: Sympa 6.1.23

[-- Attachment #1 --]
[-- Type: text/plain, Encoding: 7bit, Size: 1.6K --]

Hello

I am using GAP 4.12.2 on both Intel and M1 MAX Macs - both running Ventura
13.4, with the latest version of XCode installed.

I can successfully compile GAP and the packages on both platforms.
On an Intel Mac, everything works.
On the M1 MAX, loading packages written in GAP is fine, but loading packages
with compiled C or C++ code (like, for example, Semigroups) does not work.
Running
  LoadPackage("Semigroups"); #or also with other compiled packages

I get this error message in GAP:


Error, LOAD_DYN: failed to load kernel module /Users/lsequeir/Applications/
gap-4.12.2/pkg/semigroups/bin/aarch64-apple\
-darwin22-default64-kv8/semigroups.so, dlopen(/Users/lsequeir/Applications/
gap-4.12.2/pkg/semigroups/bin/aarch6\
4-apple-darwin22-default64-kv8/semigroups.so, 0x0005): symbol not found in
flat namespace '__ZN13libsemigroups1\
9CongruenceInterface19word_to_class_indexERKSt6vectorImSaImEE' in
  LOAD_DYN( filename ) at /Users/lsequeir/Applications/gap-4.12.2/lib/
files.gd:592 called from
<function "LoadDynamicModule">( <arguments> )
 called from read-eval loop at /Users/lsequeir/Applications/gap-4.12.2/pkg/
semigroups/init.g:22
Error, was not in any namespace at /Users/lsequeir/Applications/gap-4.12.2/
lib/variable.g:269 called from
LEAVE_NAMESPACE(  ); at /Users/lsequeir/Applications/gap-4.12.2/lib/
package.gi:1325 called from
ReadPackage( pkgname, "init.g" ); at /Users/lsequeir/Applications/gap-4.12.2/
...
```
the correct way to fix this is to test in `./configure` which C++ library should be used, and fill the template in `Makefile.in` with the correct value.

### PR DESCRIPTION
**Pull request by james-d-mitchell**
Hopefully this resolves #928. I can't test that it resolves the issue though, it works on my machine (a Mac M1), but it worked previously too. 

@dimpase are you able to check if this resolves the issue?

### CODE REVIEW

**Comment by dimpase** [comment]
I'm getting a weird `./configure` error on this PR (after running `./autogen.sh`)
```
$ ./configure            
checking for g++... no
checking for c++... c++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking for C++ compiler vendor... clang
checking whether c++ supports C++14 features by default... yes
checking for GAP root directory... /home/dima/tmp/gap
checking for GAP architecture... x86_64-unknown-openbsd7.3-default64-kv9
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```
there is GAP's `install-sh` in `../../cnf/` (I'm on current GAP master here)

**Comment by dimpase** [comment]
I presume this should be fixing #898 too - and I don't have an M1 machine to check on macOS  atm.

**Comment by dimpase** [comment]
by the way: https://github.com/semigroups/Semigroups/blob/59c5a0b3a4cab7c8f8e2f87cecfcd1e30f21e676/configure.ac#L61

- a typo?

**Comment by dimpase** [comment]
after dumping files (excluding subdirs) from `../../cnf/` to the root dir of the package, `./confugure` runs.
But the latest version of `libsemigroups` won't build:
```
make -C libsemigroups install
make[1]: Entering directory '/home/dima/tmp/gap/pkg/semigroups/libsemigroups'
./config.status gen/pkgconfig.h
  CXX      src/libsemigroups_la-bipart.lo
config.status: creating gen/pkgconfig.h
config.status: gen/pkgconfig.h is unchanged
echo > gen/pkgconfig.h.stamp
  CXX      src/libsemigroups_la-bmat8.lo
  CXX      src/libsemigroups_la-cong-intf.lo
  CXX      src/libsemigroups_la-cong-pair.lo
  CXX      src/libsemigroups_la-cong.lo
  CXX      src/libsemigroups_la-constants.lo
  CXX      src/libsemigroups_la-coset.lo
  CXX      src/libsemigroups_la-exception.lo
In file included from src/exception.cpp:33:
/home/dima/tmp/gap/pkg/semigroups/libsemigroups/extern/backward-cpp/backward.hpp:1337:25: error: no member named 'begin' in 'backward::StackTrace'
      load_addresses(st.begin(), static_cast<int>(st.size()));
                     ~~ ^
src/exception.cpp:50:8: note: in instantiation of function template specialization 'backward::TraceResolverImplBase::load_stacktrace<backward::StackTrace>' requested here
    tr.load_stacktrace(st);
       ^
1 error generated.
make[1]: *** [Makefile:3261: src/libsemigroups_la-exception.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/dima/tmp/gap/pkg/semigroups/libsemigroups'
make: *** [Makefile:88: bin/include/libsemigroups/libsemigroups.hpp] Error 2

```

**Comment by james-d-mitchell** [comment]
Thanks @dimpase, you can compile with `--disable-backward` which should fix the compilation of libsemigroups

**Comment by james-d-mitchell** [comment]
> by the way:
> 
> https://github.com/semigroups/Semigroups/blob/59c5a0b3a4cab7c8f8e2f87cecfcd1e30f21e676/configure.ac#L61
> 
> * a typo?

Well spotted!

**Comment by dimpase** [comment]
OK, built external libsemigroups, but now
```
$ CXXFLAGS="-I/home/dima/include/libsemigroups" make V=1 
"/home/dima/tmp/gap/gac" -d -p "-MQ "gen/src/cong.o" -MMD -MP -MF gen/src/cong.d" -p "-I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG  -I/usr/local/include  -I/home/dima/include/libsemigroups" -c src/cong.cpp -o gen/src/cong.o
c++ -g -O2 -fPIC -MQ gen/src/cong.o -MMD -MP -MF gen/src/cong.d -I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG -I/usr/local/include -I/home/dima/include/libsemigroups -o gen/src/cong.o -I/home/dima/tmp/gap/build -I/home/dima/tmp/gap/src -I/home/dima/tmp/gap -DUSE_GASMAN=1 -I/usr/local/include -c src/cong.cpp
In file included from src/cong.cpp:29:
In file included from src/to_cpp.hpp:61:
In file included from /home/dima/include/libsemigroups/transf.hpp:49:
In file included from /home/dima/include/libsemigroups/hpcombi.hpp:35:
In file included from /home/dima/include/libsemigroups/HPCombi/include/hpcombi.hpp:19:
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:41:9: warning: Using a constexpr broken compiler ! Performance may not be optimal [-W#pragma-messages]
#pragma message "Using a constexpr broken compiler ! "                         \
        ^
In file included from src/cong.cpp:29:
src/to_cpp.hpp:511:38: error: use of undeclared identifier 'OxFF'
      static constexpr UInt2 value = OxFF;
                                     ^
1 warning and 1 error generated.
make: *** [Makefile.gappkg:125: gen/src/cong.o] Error 1
```

turns out it's just a typo:
```diff
diff --git a/src/to_cpp.hpp b/src/to_cpp.hpp
index 37b1ac24..0bc9461c 100644
--- a/src/to_cpp.hpp
+++ b/src/to_cpp.hpp
@@ -508,7 +508,7 @@ namespace gapbind14 {
 #ifdef LIBSEMIGROUPS_HPCOMBI_ENABLED
     template <>
     struct Undef<HPCombi::PPerm16> {
-      static constexpr UInt2 value = OxFF;
+      static constexpr UInt2 value = 0xFF;
     };
 #endif
```

**Comment by dimpase** [comment]
finally, a harder one
```$ CXXFLAGS="-I/home/dima/include/libsemigroups" make V=1 
"/home/dima/tmp/gap/gac" -d -p "-MQ "gen/src/cong.o" -MMD -MP -MF gen/src/cong.d" -p "-I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG  -I/usr/local/include  -I/home/dima/include/libsemigroups" -c src/cong.cpp -o gen/src/cong.o
c++ -g -O2 -fPIC -MQ gen/src/cong.o -MMD -MP -MF gen/src/cong.d -I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG -I/usr/local/include -I/home/dima/include/libsemigroups -o gen/src/cong.o -I/home/dima/tmp/gap/build -I/home/dima/tmp/gap/src -I/home/dima/tmp/gap -DUSE_GASMAN=1 -I/usr/local/include -c src/cong.cpp
In file included from src/cong.cpp:29:
In file included from src/to_cpp.hpp:61:
In file included from /home/dima/include/libsemigroups/transf.hpp:49:
In file included from /home/dima/include/libsemigroups/hpcombi.hpp:35:
In file included from /home/dima/include/libsemigroups/HPCombi/include/hpcombi.hpp:19:
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:41:9: warning: Using a constexpr broken compiler ! Performance may not be optimal [-W#pragma-messages]
#pragma message "Using a constexpr broken compiler ! "                         \
        ^
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:205:42: error: always_inline function '_mm_testz_si128' requires target feature 'sse4.1', but would be inlined into function 'is_all_zero' that is compiled without support for 'sse4.1'
inline bool is_all_zero(epu8 a) { return _mm_testz_si128(a, a); }
                                         ^
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:215:47: error: always_inline function '_mm_shuffle_epi8' requires target feature 'ssse3', but would be inlined into function 'permuted' that is compiled without support for 'ssse3'
inline epu8 permuted(epu8 a, epu8 b) { return _mm_shuffle_epi8(a, b); }
                                              ^
1 warning and 2 errors generated.
make: *** [Makefile.gappkg:125: gen/src/cong.o] Error 1
```

**Comment by james-d-mitchell** [comment]
@dimpase you can also disable hpcombi using `--disable-hpcombi` which should allow compilation. BTW what compiler are you using, can you give the `--version` output please?

**Comment by dimpase** [comment]
```
$ c++ --version
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.3
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by dimpase** [comment]
there is a small bug in libsemigroups:
```
$ pkg-config --cflags libsemigroups
-I/home/dima/include
```
but it also needs `-I/home/dima/include/libsemigroups` there, otherwise `<Eigen/Core>` etc headers there can't be included.

I work around it by building `semigroups` like this:
```
CXXFLAGS="-I/home/dima/include/libsemigroups" make
```

Still does not build:
```
./configure -with-external-libsemigroups --disable-hpcombi 
CXXFLAGS="-I/home/dima/include/libsemigroups" make V=1

**Comment by james-d-mitchell** [comment]
Thanks @dimpase you can also disable eigen with '--disable-eigen' then hopefully everything will work!

**Comment by dimpase** [comment]
please apply
```diff
--- a/configure.ac
+++ b/configure.ac
@@ -27,7 +27,7 @@ AC_PROG_CXX
 AC_LANG([C++])
 
 AX_COMPILER_VENDOR
-AS_IF([test "x$ax_cv_c_compiler_vendor" = xclang],
+AS_IF([test "x$ax_cv_cxx_compiler_vendor" = "xclang"],
            [ AC_SUBST(CPP_STD_LIB, -lc++) ], dnl it's clang++ !
            [ AC_SUBST(CPP_STD_LIB, -lstdc++) ] )
 
```
mea culpa, I suggested the wrong `ax_cv...` variable. It doesn't work without this fix.

**Comment by dimpase** [comment]
still does not work - semigroup.so builds, has size 218Mb (sic!), and won't load:
```
$ ldd pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so                                                                                                                                                
pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so:
Cannot load specified object
pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so: exit status 1
sagemath$ file pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so 
pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so: ELF 64-bit LSB shared object, x86-64, version 1
$ ls -lh pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so 
-rwxr-xr-x  1 dima  dima   218M Jul  2 20:11 pkg/semigroups/bin/x86_64-unknown-openbsd7.3-default64-kv9/semigroups.so
```

218Mb tell me that something is off in the building process. In case, this is config.log

[config.log](https://github.com/semigroups/Semigroups/files/11931104/config.log)

**Comment by dimpase** [comment]
That is to say, this PR is a progress, but unfortunately #898 is still a problem.

**Comment by dimpase** [comment]
by looking at the output of `objdump -x semigroup.so`, to see what it is linked to, I only see
```
Dynamic Section:
  NEEDED      libc++.so.9.0
  NEEDED      libsemigroups.so.2.0
```

and this seems not a complete list. I think `libpthread.so` and `libc++abi.so are missing.

Cf. ditto for `libsemigroups.so`.
```
Dynamic Section:
  NEEDED      libpthread.so.27.0
  NEEDED      libc++.so.9.0
  NEEDED      libc++abi.so.6.0
  NEEDED      libm.so.10.1
```
`

There is also no SONAME (but it's probably OK).

So it seems that `gac` as linker is not doing the right thing here.

**Comment by dimpase** [comment]
Oops, it was due to `libsemigroups.so` installed in a non-standard directory. Setting `LD_LIBRARY_PATH` pointing there was enough for `ldd` to succeed, as well as GAP being able to load and test `semigroups` package.

So, modulo these rough spots, it's all good. Perhaps linking should be improved, using `-rpath`, so that it's less fragile.

**Comment by james-d-mitchell** [comment]
@hivert perhaps you have some insight into this?

> finally, a harder one
> 
> ```
> "/home/dima/tmp/gap/gac" -d -p "-MQ "gen/src/cong.o" -MMD -MP -MF gen/src/cong.d" -p "-I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG  -I/usr/local/include  -I/home/dima/include/libsemigroups" -c src/cong.cpp -o gen/src/cong.o
> c++ -g -O2 -fPIC -MQ gen/src/cong.o -MMD -MP -MF gen/src/cong.d -I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DFMT_HEADER_ONLY -DNDEBUG -I/usr/local/include -I/home/dima/include/libsemigroups -o gen/src/cong.o -I/home/dima/tmp/gap/build -I/home/dima/tmp/gap/src -I/home/dima/tmp/gap -DUSE_GASMAN=1 -I/usr/local/include -c src/cong.cpp
> In file included from src/cong.cpp:29:
> In file included from src/to_cpp.hpp:61:
> In file included from /home/dima/include/libsemigroups/transf.hpp:49:
> In file included from /home/dima/include/libsemigroups/hpcombi.hpp:35:
> In file included from /home/dima/include/libsemigroups/HPCombi/include/hpcombi.hpp:19:
> /home/dima/include/libsemigroups/HPCombi/include/epu.hpp:41:9: warning: Using a constexpr broken compiler ! Performance may not be optimal [-W#pragma-messages]
> #pragma message "Using a constexpr broken compiler ! "                         \
>         ^
> /home/dima/include/libsemigroups/HPCombi/include/epu.hpp:205:42: error: always_inline function '_mm_testz_si128' requires target feature 'sse4.1', but would be inlined into function 'is_all_zero' that is compiled without support for 'sse4.1'
> inline bool is_all_zero(epu8 a) { return _mm_testz_si128(a, a); }
>                                          ^
> /home/dima/include/libsemigroups/HPCombi/include/epu.hpp:215:47: error: always_inline function '_mm_shuffle_epi8' requires target feature 'ssse3', but would be inlined into function 'permuted' that is compiled without support for 'ssse3'
> inline epu8 permuted(epu8 a, epu8 b) { return _mm_shuffle_epi8(a, b); }
>                                               ^
> 1 warning and 2 errors generated.
> make: *** [Makefile.gappkg:125: gen/src/cong.o] Error 1
> ```

**Comment by hivert** [comment]
> @hivert perhaps you have some insight into this?
'_mm_shuffle_epi8' requires target feature 'ssse3', but would be inlined into function 'permuted' that is compiled without support for 'ssse3'

My understanding of the error message is that your are trying to compile HPCombi without setting the compiler to use 'sse4.1` and 'sse3' instructions sets. Those are currently mandatory for HPCombi, and should be set by the CMAKE build system if you use it. If you don't want to build for those architecture, you should simply deactivate the HPCombi support in your build system. It won't work at all without those architecture flags. HPCombi is designed to be highly optimized at the cost of portability.

**Comment by hivert** [comment]
> warning: Using a constexpr broken compiler ! Performance may not be optimal

This message signal that HPCOMBI_CONSTEXPR_FUN_ARGS is not defined. I had some problems with some old compiler (G++ 5.0 according to the notes) with constexpr function as arguments so I'm testing it in my configure and defining this variable. libsemigroup ported the same test in its configuration script. I guess libsemigroups configure script is not properly run.

For reference, here is the CMake tests:

```
## Check for buggy constexpr support G++ 5.0
check_cxx_source_compiles(
  "
  using T = int;
  constexpr int exec(T f()) { return f(); }
  constexpr int foo() { return 1; }
  static_assert(exec(foo) == 1, \"Failed exec\");
  int main() {}
  "
  HPCOMBI_CONSTEXPR_FUN_ARGS)
```

**Comment by dimpase** [comment]
I cannot imagine clang 13 having problems with standard C++ features.
So probably something is off with the corresponding test.

**Comment by hivert** [comment]
> I cannot imagine clang 13 having problems with standard C++ features. So probably something is off with the corresponding test.

My guess is that there is something wrong with the configure/build system. I need to see some log and configure output to know more.

**Comment by dimpase** [comment]
OK, I've built and installed  libsemigroup with HPCombi enabled, but then while configuring `semigroup` GAP package I get

```
$ LD_LIBRARY_PATH=/home/dima/lib ./configure -with-external-libsemigroups
...
checking for stdint.h... yes
checking for unistd.h... yes
checking whether to enable HPCombi... yes
configure: WARNING: HPCombi is not available
configure: creating ./config.status
config.status: creating Makefile
...
```
 `m4/ax_check_hpcombi.m4`   has
```m4
   AS_IF([test "x$enable_hpcombi" = xyes],
        [AS_IF([test -f $srcdir/extern/HPCombi/VERSION], 
                       [], 
                       [AC_MSG_WARN([HPCombi is not available])
                       [enable_hpcombi=no]])])
```
to test for presence of HPCombi in a rather unorthodox (and just wrong) way.
This won't work with external libseimgroups. 
Moreover, this `VERSION` file didn't get installed (only headers get installed).

Normally speaking, a library like HPCombi should have a function or a macro returning version, not some kind of
non-standard file with version written into it.

```
$ ls /home/dima/include/libsemigroups/HPCombi/         
include
```

[libsemigroup config.log](https://github.com/semigroups/Semigroups/files/12016010/config.log)
[semigroup GAP package config.log](https://github.com/semigroups/Semigroups/files/12016016/semigroup.config.log)

**Comment by dimpase** [comment]
If I modify autoconf macros to get rid of VERSION check, ./cofigure passes OK, but
``
`$ CXXFLAGS="-I/home/dima/include/libsemigroups" make 
   GAC     src/cong.cpp => gen/src/cong.o
In file included from src/cong.cpp:29:
In file included from src/to_cpp.hpp:61:
In file included from /home/dima/include/libsemigroups/transf.hpp:49:
In file included from /home/dima/include/libsemigroups/hpcombi.hpp:35:
In file included from /home/dima/include/libsemigroups/HPCombi/include/hpcombi.hpp:19:
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:205:42: error: always_inline function '_mm_testz_si128' requires target feature 'sse4.1', but would be inlined into function 'is_all_zero' that is compiled without support for 'sse4.1'
inline bool is_all_zero(epu8 a) { return _mm_testz_si128(a, a); }
                                         ^
/home/dima/include/libsemigroups/HPCombi/include/epu.hpp:215:47: error: always_inline function '_mm_shuffle_epi8' requires target feature 'ssse3', but would be inlined into function 'permuted' that is compiled without support for 'ssse3'
inline epu8 permuted(epu8 a, epu8 b) { return _mm_shuffle_epi8(a, b); }
                                              ^
2 errors generated.
```

**Comment by dimpase** [comment]
Explicitly adding ` -msse4.1` to `CXXFLAGS` make the last error go away. So this is something checkable in `./configure`, I presume.

**Comment by dimpase** [comment]
But still it errors out with C++ errors:
```
"/home/dima/tmp/gap/gac" -d -p "-MQ "gen/src/froidure-pin-pperm.o" -MMD -MP -MF gen/src/froidure-pin-pperm.d" -p "-I/home/dima/include -std=gnu++14 -O3  -Igapbind14/include/ -DHPCOMBI_CONSTEXPR_FUN_ARGS -DFMT_HEADER_ONLY -DNDEBUG  -I/usr/local/include  -I/home/dima/include/ -I/home/dima/include/libsemigroups -msse4.1" -c src/froidure-pin-pperm.cpp -o gen/src/froidure-pin-pperm.o
c++ -g -O2 -fPIC -MQ gen/src/froidure-pin-pperm.o -MMD -MP -MF gen/src/froidure-pin-pperm.d -I/home/dima/include -std=gnu++14 -O3 -Igapbind14/include/ -DHPCOMBI_CONSTEXPR_FUN_ARGS -DFMT_HEADER_ONLY -DNDEBUG -I/usr/local/include -I/home/dima/include/ -I/home/dima/include/libsemigroups -msse4.1 -o gen/src/froidure-pin-pperm.o -I/home/dima/tmp/gap/build -I/home/dima/tmp/gap/src -I/home/dima/tmp/gap -DUSE_GASMAN=1 -I/usr/local/include -c src/froidure-pin-pperm.cpp
In file included from src/froidure-pin-pperm.cpp:20:
In file included from src/froidure-pin.hpp:30:
In file included from gapbind14/include/gapbind14/gapbind14.hpp:45:
In file included from gapbind14/include/gapbind14/tame_free_fn.hpp:29:
gapbind14/include/gapbind14/to_cpp.hpp:48:9: error: implicit instantiation of undefined template 'gapbind14::to_cpp<HPCombi::PPerm16>'
      : to_cpp<T> {};
        ^
gapbind14/include/gapbind14/tame_mem_fn.hpp:88:38: note: in instantiation of template class 'gapbind14::to_cpp<const HPCombi::PPerm16 &>' requested here
          wild_mem_fn<Wild>(N), ptr, to_cpp<to_cpp_1_type>()(arg1)));
                                     ^
gapbind14/include/gapbind14/tame_mem_fn.hpp:525:22: note: in instantiation of function template specialization 'gapbind14::detail::tame_mem_fn<63UL, void (libsemigroups::FroidurePin<HPCombi::PPerm16>::*)(const HPCombi::PPerm16 &), OpaqueBag *>' requested here
        v.push_back(&tame_mem_fn<N - 1, Wild>);
                     ^
gapbind14/include/gapbind14/tame_mem_fn.hpp:540:7: note: in instantiation of member function 'gapbind14::detail::static_push_back_mem_fns<64, OpaqueBag *(*)(OpaqueBag *, OpaqueBag *, OpaqueBag *), void (libsemigroups::FroidurePin<HPCombi::PPerm16>::*)(const HPCombi::PPerm16 &)>::operator()' requested here
      static_push_back_mem_fns<MAX_FUNCTIONS, Tame, Wild>{}(fs);
      ^
src/froidure-pin.hpp:65:8: note: in instantiation of function template specialization 'gapbind14::class_<libsemigroups::FroidurePin<HPCombi::PPerm16>>::def<void (libsemigroups::FroidurePin<HPCombi::PPerm16>::*)(const HPCombi::PPerm16 &)>' requested here
      .def("add_generator", &FroidurePin_::add_generator)
       ^
src/froidure-pin-pperm.cpp:40:3: note: in instantiation of function template specialization 'bind_froidure_pin<HPCombi::PPerm16>' requested here
  bind_froidure_pin<LeastPPerm<16>>(m, "FroidurePinPPerm16");
  ^
gapbind14/include/gapbind14/to_cpp.hpp:38:10: note: template is declared here
  struct to_cpp;
         ^
...
```

So it's probably a generic clang error, not something OpenBSD specific.

attached the full log here:
[ma.log](https://github.com/semigroups/Semigroups/files/12029159/ma.log)

**Comment by hivert** [comment]
> Normally speaking, a library like HPCombi should have a function or a macro returning version, not some kind of non-standard file with version written into it.

I has if configured normally through CMake (via config.h). However, since HPCombi is a header only library, @james-d-mitchell decided to just copy the file (including the version file) and rely on a custom autotools config. I guess the problem with that.

**Comment by dimpase** [comment]
I am trying to see what happens if I install HPCombi separately, and I don't see it installing (with `cmake -DCMAKE_INSTALL_PREFIX=/foo/bar && make && make install`) anything into `$prefix/lib/cmake/` - which is the location needed by `cmake` to do package discovery. You also don't install `hpcombi.pc`, even though you have the template `hpcombi.pc.in` - and this prevents `pkg-config` usage for version discovery, too.

You do copy `VERSION` into `$prefix/` - but this is  making no sense; note that `$prefix`, i..e. what you specify with `-DCMAKE_INSTALL_PREFIX=...` is typically something like `/usr/local` placing a file named `VERSION` right there makes no sense.

**Comment by dimpase** [comment]
I've opened https://github.com/hivert/HPCombi/issues/15 to spell out what I wrote just now there, too.

**Comment by dimpase** [comment]
> I has if configured normally through CMake (via config.h).

I don't know what `config.h` you mean. Normally speaking, `config.h` is an internal header - anyway, HPCombi's `make install` does not copy `config.h` anywhere.

One way or another, `HPCombi` is vendored by `libsemigroups`, and that's from this point on entirely on vendor to make sure the version is correct. I don't see why `semigroup` even needs to check `HPCombi`'s version, it should know that a proper `libsemigroup` version contains proper version of `HPCombi`'.

**Pull request closed without merging**
