### PR TITLE
Fix DOI image link in README + minor edits

### PR DESCRIPTION
**Pull request by slel**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Thanks @slel! Happy to merge!

**Comment by alex-konovalov** [comment]
Interesting @slel ! I didn't know that Zenodo updated URLs for badges. Checked on a recent repository I've archived there - the markdown code that is shown when I click on a badge refers to zenodo.org, not to img.shields.io:
```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4710733.svg)](https://doi.org/10.5281/zenodo.4710733)
```

**Comment by alex-konovalov** [comment]
But last week there were issues with Zenodo DOI badges not displayed on GitHub repositories. They seem fixed by now. Was you change an attempt to fix the badge in a different way?

**Comment by slel** [comment]
This was to fix the image not displaying.
Fixed elsewhere, so let's close this.

**Comment by slel** [comment]
(Following a problem installing GAP packages in Sage:

- https://groups.google.com/g/sage-devel/c/4TNR6K0iT7I

I was looking for hints in the installation instructions.)

**Pull request closed without merging**
