### PR TITLE
Replace some uses of IMMUTABLE

### PR DESCRIPTION
**Pull request by fingolfin**
Use of IMMUTABLE is an internal kernel detail, and there are some plans
to eventually move it from a bit in the TNUM to a separate object flag
at some point.

### CODE REVIEW

**Review by wilfwilson — APPROVED** [review]
Looks fine to me, thanks.

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin, I'm also happy with this in principle, I'll have to resurrect the CI just to ensure that everything still works, before merging.

**Comment by fingolfin** [comment]
FYI @ssiccha started working on bringing GH Actions support to GAP packages; first step was in https://github.com/gap-packages/recog/pull/202, right now we are working on turning these steps into "actions" so we can update them centrally, see https://github.com/gap-packages/recog/pull/210

This is very similar to what we used so far on Travis for most packages (but I think Semigroups and Digraphs where two of the big exceptions). And this does not (yet!) use Docker and/or prebuilt binaries, simply because we wanted to get something working ASAP. 

Also, the homalg team, in particular @zickgraf and @mohamed-barakat have been working on using GitHub Actions for their GAP packages; see e.g. https://github.com/homalg-project/homalg_project/tree/master/.github/workflows and https://github.com/homalg-project/CatReps/blob/master/.github/workflows/Tests.yml

I don't know if any of this is useful for you, but I wanted to make sure you know about it, just in case; also I hope we can benefit from each other's work and experience :-)

**Comment by zickgraf** [comment]
One important piece of information for using the GAP docker container in GitHub Actions: When I created our CI, I could not access the results of `actions/checkout@v2` from inside the container. My solution was to use `actions/checkout@v1` instead. With that you can simply copy the result to the appropriate location: `sudo cp -a $GITHUB_WORKSPACE /home/gap/.gap/pkg/`.

**Comment by fingolfin** [comment]
Just FYI, you can also close and reopen a PR to trigger CI against the latest version of the bade branch

**Comment by james-d-mitchell** [comment]
> FYI @ssiccha started working on bringing GH Actions support to GAP packages; first step was in [gap-packages/recog#202](https://github.com/gap-packages/recog/pull/202), right now we are working on turning these steps into "actions" so we can update them centrally, see [gap-packages/recog#210](https://github.com/gap-packages/recog/pull/210)
> 
> This is very similar to what we used so far on Travis for most packages (but I think Semigroups and Digraphs where two of the big exceptions). And this does not (yet!) use Docker and/or prebuilt binaries, simply because we wanted to get something working ASAP.
> 
> Also, the homalg team, in particular @zickgraf and @mohamed-barakat have been working on using GitHub Actions for their GAP packages; see e.g. https://github.com/homalg-project/homalg_project/tree/master/.github/workflows and https://github.com/homalg-project/CatReps/blob/master/.github/workflows/Tests.yml
> 
> I don't know if any of this is useful for you, but I wanted to make sure you know about it, just in case; also I hope we can benefit from each other's work and experience :-)

Thanks for this @fingolfin, I didn't read this until now, some how overlooked it. I think the Semigroups and Digraphs travis stuff predated the gap-packages stuff which is why we used a different setup, if I recall correctly.

**Pull request merged**
