### PR TITLE
Better Nambooripad

### PR DESCRIPTION
**Pull request by Tianrun-Y**
A faster way of finding the Nambooripad Partial Order (aka natural partial order and Mitsch order) of a finite regular semigroup.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Thanks for the contribution @Tianrun-Y, can you please give an example which indicates why we should prefer the new method over the older method?

**Comment by Tianrun-Y** [comment]
Old version
gap> S:=FullTransformationMonoid(4);;
gap> NambooripadPartialOrder(S);;time;
3445

New version
gap> S:=FullTransformationMonoid(4);;
gap> NambooripadPartialOrder(S);;time;
136

**Comment by james-d-mitchell** [comment]
Can you please add the example to the relevant test file? Then I'll be happy to merge, and thanks very much!

**Comment by Tianrun-Y** [comment]
> Can you please add the example to the relevant test file? Then I'll be happy to merge, and thanks very much!

Test added with time included as a comment. Hope this is good?

**Review by james-d-mitchell — APPROVED** [review]

**Pull request merged**
